//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client.HostelReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://endpoint.service/", ConfigurationName="HostelReference.HostelService")]
    public interface HostelService {
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.service/HostelService/getAllHostelRequest", ReplyAction="http://endpoint.service/HostelService/getAllHostelResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        client.HostelReference.getAllHostelResponse getAllHostel(client.HostelReference.getAllHostelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.service/HostelService/getAllHostelRequest", ReplyAction="http://endpoint.service/HostelService/getAllHostelResponse")]
        System.Threading.Tasks.Task<client.HostelReference.getAllHostelResponse> getAllHostelAsync(client.HostelReference.getAllHostelRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.service/HostelService/setNewHostelRequest", ReplyAction="http://endpoint.service/HostelService/setNewHostelResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        client.HostelReference.setNewHostelResponse setNewHostel(client.HostelReference.setNewHostelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.service/HostelService/setNewHostelRequest", ReplyAction="http://endpoint.service/HostelService/setNewHostelResponse")]
        System.Threading.Tasks.Task<client.HostelReference.setNewHostelResponse> setNewHostelAsync(client.HostelReference.setNewHostelRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.service/HostelService/setDelHostelRequest", ReplyAction="http://endpoint.service/HostelService/setDelHostelResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        client.HostelReference.setDelHostelResponse setDelHostel(client.HostelReference.setDelHostelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.service/HostelService/setDelHostelRequest", ReplyAction="http://endpoint.service/HostelService/setDelHostelResponse")]
        System.Threading.Tasks.Task<client.HostelReference.setDelHostelResponse> setDelHostelAsync(client.HostelReference.setDelHostelRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.service/HostelService/getSumOfHostelRequest", ReplyAction="http://endpoint.service/HostelService/getSumOfHostelResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        client.HostelReference.getSumOfHostelResponse getSumOfHostel(client.HostelReference.getSumOfHostelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.service/HostelService/getSumOfHostelRequest", ReplyAction="http://endpoint.service/HostelService/getSumOfHostelResponse")]
        System.Threading.Tasks.Task<client.HostelReference.getSumOfHostelResponse> getSumOfHostelAsync(client.HostelReference.getSumOfHostelRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://endpoint.service/")]
    public partial class hostel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int kolField;
        
        private string nameField;
        
        private int numberField;
        
        private int priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int kol {
            get {
                return this.kolField;
            }
            set {
                this.kolField = value;
                this.RaisePropertyChanged("kol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllHostel", WrapperNamespace="http://endpoint.service/", IsWrapped=true)]
    public partial class getAllHostelRequest {
        
        public getAllHostelRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllHostelResponse", WrapperNamespace="http://endpoint.service/", IsWrapped=true)]
    public partial class getAllHostelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.service/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public client.HostelReference.hostel[] @return;
        
        public getAllHostelResponse() {
        }
        
        public getAllHostelResponse(client.HostelReference.hostel[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setNewHostel", WrapperNamespace="http://endpoint.service/", IsWrapped=true)]
    public partial class setNewHostelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public client.HostelReference.hostel arg0;
        
        public setNewHostelRequest() {
        }
        
        public setNewHostelRequest(client.HostelReference.hostel arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setNewHostelResponse", WrapperNamespace="http://endpoint.service/", IsWrapped=true)]
    public partial class setNewHostelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.service/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public client.HostelReference.hostel[] @return;
        
        public setNewHostelResponse() {
        }
        
        public setNewHostelResponse(client.HostelReference.hostel[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setDelHostel", WrapperNamespace="http://endpoint.service/", IsWrapped=true)]
    public partial class setDelHostelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public setDelHostelRequest() {
        }
        
        public setDelHostelRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setDelHostelResponse", WrapperNamespace="http://endpoint.service/", IsWrapped=true)]
    public partial class setDelHostelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.service/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public client.HostelReference.hostel[] @return;
        
        public setDelHostelResponse() {
        }
        
        public setDelHostelResponse(client.HostelReference.hostel[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSumOfHostel", WrapperNamespace="http://endpoint.service/", IsWrapped=true)]
    public partial class getSumOfHostelRequest {
        
        public getSumOfHostelRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSumOfHostelResponse", WrapperNamespace="http://endpoint.service/", IsWrapped=true)]
    public partial class getSumOfHostelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public getSumOfHostelResponse() {
        }
        
        public getSumOfHostelResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HostelServiceChannel : client.HostelReference.HostelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HostelServiceClient : System.ServiceModel.ClientBase<client.HostelReference.HostelService>, client.HostelReference.HostelService {
        
        public HostelServiceClient() {
        }
        
        public HostelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HostelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HostelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HostelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client.HostelReference.getAllHostelResponse client.HostelReference.HostelService.getAllHostel(client.HostelReference.getAllHostelRequest request) {
            return base.Channel.getAllHostel(request);
        }
        
        public client.HostelReference.hostel[] getAllHostel() {
            client.HostelReference.getAllHostelRequest inValue = new client.HostelReference.getAllHostelRequest();
            client.HostelReference.getAllHostelResponse retVal = ((client.HostelReference.HostelService)(this)).getAllHostel(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client.HostelReference.getAllHostelResponse> client.HostelReference.HostelService.getAllHostelAsync(client.HostelReference.getAllHostelRequest request) {
            return base.Channel.getAllHostelAsync(request);
        }
        
        public System.Threading.Tasks.Task<client.HostelReference.getAllHostelResponse> getAllHostelAsync() {
            client.HostelReference.getAllHostelRequest inValue = new client.HostelReference.getAllHostelRequest();
            return ((client.HostelReference.HostelService)(this)).getAllHostelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client.HostelReference.setNewHostelResponse client.HostelReference.HostelService.setNewHostel(client.HostelReference.setNewHostelRequest request) {
            return base.Channel.setNewHostel(request);
        }
        
        public client.HostelReference.hostel[] setNewHostel(client.HostelReference.hostel arg0) {
            client.HostelReference.setNewHostelRequest inValue = new client.HostelReference.setNewHostelRequest();
            inValue.arg0 = arg0;
            client.HostelReference.setNewHostelResponse retVal = ((client.HostelReference.HostelService)(this)).setNewHostel(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client.HostelReference.setNewHostelResponse> client.HostelReference.HostelService.setNewHostelAsync(client.HostelReference.setNewHostelRequest request) {
            return base.Channel.setNewHostelAsync(request);
        }
        
        public System.Threading.Tasks.Task<client.HostelReference.setNewHostelResponse> setNewHostelAsync(client.HostelReference.hostel arg0) {
            client.HostelReference.setNewHostelRequest inValue = new client.HostelReference.setNewHostelRequest();
            inValue.arg0 = arg0;
            return ((client.HostelReference.HostelService)(this)).setNewHostelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client.HostelReference.setDelHostelResponse client.HostelReference.HostelService.setDelHostel(client.HostelReference.setDelHostelRequest request) {
            return base.Channel.setDelHostel(request);
        }
        
        public client.HostelReference.hostel[] setDelHostel(int arg0) {
            client.HostelReference.setDelHostelRequest inValue = new client.HostelReference.setDelHostelRequest();
            inValue.arg0 = arg0;
            client.HostelReference.setDelHostelResponse retVal = ((client.HostelReference.HostelService)(this)).setDelHostel(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client.HostelReference.setDelHostelResponse> client.HostelReference.HostelService.setDelHostelAsync(client.HostelReference.setDelHostelRequest request) {
            return base.Channel.setDelHostelAsync(request);
        }
        
        public System.Threading.Tasks.Task<client.HostelReference.setDelHostelResponse> setDelHostelAsync(int arg0) {
            client.HostelReference.setDelHostelRequest inValue = new client.HostelReference.setDelHostelRequest();
            inValue.arg0 = arg0;
            return ((client.HostelReference.HostelService)(this)).setDelHostelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client.HostelReference.getSumOfHostelResponse client.HostelReference.HostelService.getSumOfHostel(client.HostelReference.getSumOfHostelRequest request) {
            return base.Channel.getSumOfHostel(request);
        }
        
        public int getSumOfHostel() {
            client.HostelReference.getSumOfHostelRequest inValue = new client.HostelReference.getSumOfHostelRequest();
            client.HostelReference.getSumOfHostelResponse retVal = ((client.HostelReference.HostelService)(this)).getSumOfHostel(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client.HostelReference.getSumOfHostelResponse> client.HostelReference.HostelService.getSumOfHostelAsync(client.HostelReference.getSumOfHostelRequest request) {
            return base.Channel.getSumOfHostelAsync(request);
        }
        
        public System.Threading.Tasks.Task<client.HostelReference.getSumOfHostelResponse> getSumOfHostelAsync() {
            client.HostelReference.getSumOfHostelRequest inValue = new client.HostelReference.getSumOfHostelRequest();
            return ((client.HostelReference.HostelService)(this)).getSumOfHostelAsync(inValue);
        }
    }
}
