
package service.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HostelServiceService", targetNamespace = "http://endpoint.service/", wsdlLocation = "http://localhost:8080/ws02/HostelService?wsdl")
public class HostelServiceService
    extends Service
{

    private final static URL HOSTELSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException HOSTELSERVICESERVICE_EXCEPTION;
    private final static QName HOSTELSERVICESERVICE_QNAME = new QName("http://endpoint.service/", "HostelServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws02/HostelService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOSTELSERVICESERVICE_WSDL_LOCATION = url;
        HOSTELSERVICESERVICE_EXCEPTION = e;
    }

    public HostelServiceService() {
        super(__getWsdlLocation(), HOSTELSERVICESERVICE_QNAME);
    }

    public HostelServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOSTELSERVICESERVICE_QNAME, features);
    }

    public HostelServiceService(URL wsdlLocation) {
        super(wsdlLocation, HOSTELSERVICESERVICE_QNAME);
    }

    public HostelServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOSTELSERVICESERVICE_QNAME, features);
    }

    public HostelServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HostelServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HostelService
     */
    @WebEndpoint(name = "HostelServicePort")
    public HostelService getHostelServicePort() {
        return super.getPort(new QName("http://endpoint.service/", "HostelServicePort"), HostelService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HostelService
     */
    @WebEndpoint(name = "HostelServicePort")
    public HostelService getHostelServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.service/", "HostelServicePort"), HostelService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOSTELSERVICESERVICE_EXCEPTION!= null) {
            throw HOSTELSERVICESERVICE_EXCEPTION;
        }
        return HOSTELSERVICESERVICE_WSDL_LOCATION;
    }

}
