
package service.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import types.Hostel;
import types.ListOfHostel;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HostelService", targetNamespace = "http://endpoint.service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HostelService {


    /**
     * 
     * @return
     *     returns service.endpoint.ListOfHostel
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllHostel", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetAllHostel")
    @ResponseWrapper(localName = "getAllHostelResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetAllHostelResponse")
    @Action(input = "http://endpoint.service/HostelService/getAllHostelRequest", output = "http://endpoint.service/HostelService/getAllHostelResponse")
    public ListOfHostel getAllHostel();

    /**
     * 
     * @param arg0
     * @return
     *     returns service.endpoint.ListOfHostel
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setNewHostel", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetNewHostel")
    @ResponseWrapper(localName = "setNewHostelResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetNewHostelResponse")
    @Action(input = "http://endpoint.service/HostelService/setNewHostelRequest", output = "http://endpoint.service/HostelService/setNewHostelResponse")
    public ListOfHostel setNewHostel(
        @WebParam(name = "arg0", targetNamespace = "")
        Hostel arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.endpoint.ListOfHostel
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setDelHostel", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetDelHostel")
    @ResponseWrapper(localName = "setDelHostelResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetDelHostelResponse")
    @Action(input = "http://endpoint.service/HostelService/setDelHostelRequest", output = "http://endpoint.service/HostelService/setDelHostelResponse")
    public ListOfHostel setDelHostel(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSumOfHostel", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetSumOfHostel")
    @ResponseWrapper(localName = "getSumOfHostelResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetSumOfHostelResponse")
    @Action(input = "http://endpoint.service/HostelService/getSumOfHostelRequest", output = "http://endpoint.service/HostelService/getSumOfHostelResponse")
    public int getSumOfHostel();

}
