
package service.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import types.ListOfService;
import types.Service;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceService", targetNamespace = "http://endpoint.service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceService {


    /**
     * 
     * @return
     *     returns service.endpoint.ListOfService
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllService", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetAllService")
    @ResponseWrapper(localName = "getAllServiceResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetAllServiceResponse")
    @Action(input = "http://endpoint.service/ServiceService/getAllServiceRequest", output = "http://endpoint.service/ServiceService/getAllServiceResponse")
    public ListOfService getAllService();

    /**
     * 
     * @param arg0
     * @return
     *     returns service.endpoint.ListOfService
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setDelService", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetDelService")
    @ResponseWrapper(localName = "setDelServiceResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetDelServiceResponse")
    @Action(input = "http://endpoint.service/ServiceService/setDelServiceRequest", output = "http://endpoint.service/ServiceService/setDelServiceResponse")
    public ListOfService setDelService(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.endpoint.ListOfService
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setNewService", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetNewService")
    @ResponseWrapper(localName = "setNewServiceResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetNewServiceResponse")
    @Action(input = "http://endpoint.service/ServiceService/setNewServiceRequest", output = "http://endpoint.service/ServiceService/setNewServiceResponse")
    public ListOfService setNewService(
        @WebParam(name = "arg0", targetNamespace = "")
        Service arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSumOfService", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetSumOfService")
    @ResponseWrapper(localName = "getSumOfServiceResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetSumOfServiceResponse")
    @Action(input = "http://endpoint.service/ServiceService/getSumOfServiceRequest", output = "http://endpoint.service/ServiceService/getSumOfServiceResponse")
    public int getSumOfService();

}
