
package service.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceServiceService", targetNamespace = "http://endpoint.service/", wsdlLocation = "http://localhost:8080/ws02/ServicelService?wsdl")
public class ServiceServiceService
    extends Service
{

    private final static URL SERVICESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICESERVICESERVICE_EXCEPTION;
    private final static QName SERVICESERVICESERVICE_QNAME = new QName("http://endpoint.service/", "ServiceServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws02/ServicelService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICESERVICESERVICE_WSDL_LOCATION = url;
        SERVICESERVICESERVICE_EXCEPTION = e;
    }

    public ServiceServiceService() {
        super(__getWsdlLocation(), SERVICESERVICESERVICE_QNAME);
    }

    public ServiceServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICESERVICESERVICE_QNAME, features);
    }

    public ServiceServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICESERVICESERVICE_QNAME);
    }

    public ServiceServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICESERVICESERVICE_QNAME, features);
    }

    public ServiceServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceService
     */
    @WebEndpoint(name = "ServiceServicePort")
    public ServiceService getServiceServicePort() {
        return super.getPort(new QName("http://endpoint.service/", "ServiceServicePort"), ServiceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceService
     */
    @WebEndpoint(name = "ServiceServicePort")
    public ServiceService getServiceServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.service/", "ServiceServicePort"), ServiceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICESERVICESERVICE_EXCEPTION!= null) {
            throw SERVICESERVICESERVICE_EXCEPTION;
        }
        return SERVICESERVICESERVICE_WSDL_LOCATION;
    }

}
