package base;

/**
 *
 * @author Lactea Via
 */
import java.util.List;
import javax.swing.table.DefaultTableModel;
import operation.TovarOperationImpl;
import types.Tovar;

public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrp = new javax.swing.ButtonGroup();
        dlgAdd = new javax.swing.JDialog();
        lblName = new javax.swing.JLabel();
        lblKol = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblPriceInfo = new javax.swing.JLabel();
        cmbName = new javax.swing.JComboBox<>();
        spnKol = new javax.swing.JSpinner();
        scrPrice = new javax.swing.JScrollBar();
        pnlConstruct = new javax.swing.JPanel();
        rdbNoParam = new javax.swing.JRadioButton();
        rdbYesParam = new javax.swing.JRadioButton();
        btnAddTovar = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        lbl = new java.awt.Label();
        txtTotalSumma = new java.awt.TextField();
        tlBar = new javax.swing.JToolBar();
        btnAdd = new javax.swing.JButton();
        spr1 = new javax.swing.JToolBar.Separator();
        btnDecide = new javax.swing.JButton();
        spr2 = new javax.swing.JToolBar.Separator();
        btnExit = new javax.swing.JButton();

        dlgAdd.setTitle("Окно ввода");
        dlgAdd.setName("dlgAdd"); // NOI18N

        lblName.setText("Наименование");
        lblName.setName("lblName"); // NOI18N

        lblKol.setText("Количество");
        lblKol.setName("lblKol"); // NOI18N

        lblPrice.setText("Цена");
        lblPrice.setName("lblPrice"); // NOI18N

        lblPriceInfo.setText("50");
        lblPriceInfo.setName("lblPriceInfo"); // NOI18N

        cmbName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Тетрадь", "Ручка", "Карандаш" }));
        cmbName.setName("cmbName"); // NOI18N

        spnKol.setModel(new javax.swing.SpinnerNumberModel(10, 1, 30, 2));
        spnKol.setToolTipText("");
        spnKol.setName("spnKol"); // NOI18N

        scrPrice.setMinimum(5);
        scrPrice.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        scrPrice.setValue(50);
        scrPrice.setName("scrPrice"); // NOI18N
        scrPrice.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                scrPriceAdjustmentValueChanged(evt);
            }
        });

        pnlConstruct.setBorder(javax.swing.BorderFactory.createTitledBorder("Конструктор"));
        pnlConstruct.setName("pnlConstruct"); // NOI18N

        btnGrp.add(rdbNoParam);
        rdbNoParam.setSelected(true);
        rdbNoParam.setText("без параметров");
        rdbNoParam.setName("rdbNoParam"); // NOI18N

        rdbYesParam.setText("с параметрами");
        rdbYesParam.setName("rdbYesParam"); // NOI18N

        org.jdesktop.layout.GroupLayout pnlConstructLayout = new org.jdesktop.layout.GroupLayout(pnlConstruct);
        pnlConstruct.setLayout(pnlConstructLayout);
        pnlConstructLayout.setHorizontalGroup(
            pnlConstructLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlConstructLayout.createSequentialGroup()
                .addContainerGap()
                .add(rdbNoParam)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(rdbYesParam)
                .addContainerGap())
        );
        pnlConstructLayout.setVerticalGroup(
            pnlConstructLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlConstructLayout.createSequentialGroup()
                .add(23, 23, 23)
                .add(pnlConstructLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(rdbNoParam)
                    .add(rdbYesParam))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnAddTovar.setText("Добавить");
        btnAddTovar.setName("btnAddTovar"); // NOI18N
        btnAddTovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTovarActionPerformed(evt);
            }
        });

        btnCancel.setActionCommand("Отмена");
        btnCancel.setLabel("Отмена");
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout dlgAddLayout = new org.jdesktop.layout.GroupLayout(dlgAdd.getContentPane());
        dlgAdd.getContentPane().setLayout(dlgAddLayout);
        dlgAddLayout.setHorizontalGroup(
            dlgAddLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dlgAddLayout.createSequentialGroup()
                .add(dlgAddLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(dlgAddLayout.createSequentialGroup()
                        .add(22, 22, 22)
                        .add(lblPrice)
                        .add(18, 18, 18)
                        .add(scrPrice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 17, Short.MAX_VALUE))
                    .add(dlgAddLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(dlgAddLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblName)
                            .add(lblKol))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(dlgAddLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(cmbName, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(dlgAddLayout.createSequentialGroup()
                                .add(spnKol)
                                .add(87, 87, 87)))))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, dlgAddLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(lblPriceInfo)
                .add(97, 97, 97))
            .add(dlgAddLayout.createSequentialGroup()
                .addContainerGap()
                .add(dlgAddLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(dlgAddLayout.createSequentialGroup()
                        .add(pnlConstruct, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(dlgAddLayout.createSequentialGroup()
                        .add(btnAddTovar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btnCancel)
                        .add(22, 22, 22))))
        );
        dlgAddLayout.setVerticalGroup(
            dlgAddLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dlgAddLayout.createSequentialGroup()
                .addContainerGap()
                .add(dlgAddLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblName)
                    .add(cmbName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(15, 15, 15)
                .add(dlgAddLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblKol)
                    .add(spnKol, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dlgAddLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(dlgAddLayout.createSequentialGroup()
                        .add(lblPriceInfo)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(scrPrice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(lblPrice))
                .add(18, 18, 18)
                .add(pnlConstruct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dlgAddLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnAddTovar)
                    .add(btnCancel))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Работа №1");
        setName("form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "№ п/п", "Название", "Цена", "Количество", "Сумма"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.setName("tbl"); // NOI18N
        jScrollPane1.setViewportView(tbl);

        lbl.setName("lbl"); // NOI18N
        lbl.setText("Общая сумма товара");

        txtTotalSumma.setName("txtTotalSumma"); // NOI18N

        tlBar.setRollover(true);
        tlBar.setName("tlBar"); // NOI18N

        btnAdd.setText("Добавить");
        btnAdd.setFocusTraversalPolicyProvider(true);
        btnAdd.setFocusable(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setName("btnAdd"); // NOI18N
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        tlBar.add(btnAdd);
        tlBar.add(spr1);

        btnDecide.setText("Вычислить");
        btnDecide.setFocusable(false);
        btnDecide.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDecide.setName(""); // NOI18N
        btnDecide.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDecide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecideActionPerformed(evt);
            }
        });
        tlBar.add(btnDecide);
        tlBar.add(spr2);

        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setLabel("Выход");
        btnExit.setName("btnExit"); // NOI18N
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        tlBar.add(btnExit);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(lbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(49, 49, 49)
                                .add(txtTotalSumma, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 133, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 375, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(tlBar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(tlBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 176, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(24, 24, 24)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(lbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtTotalSumma, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    TovarOperationImpl tovarOperation = new TovarOperationImpl();
    static DefaultTableModel model = new DefaultTableModel();

    private void btnDecideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecideActionPerformed
      txtTotalSumma.setText(Integer.toString(tovarOperation.getSumOfTovar()));
    }//GEN-LAST:event_btnDecideActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        dlgAdd.setSize(300, 320);
        dlgAdd.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed
                                                                                                                                       

    private void doVivod(List<Tovar> lstTovar){
        doClearTable();
        int i = 1;
        for(Tovar tovar: lstTovar){
            Object[] rowData = new Object[5];
            rowData[0] = i++;
            rowData[1] = tovar.getName();
            rowData[2] = tovar.getPrice();
            rowData[3] = tovar.getKol();
            rowData[4] = tovar.getPrice() * tovar.getKol();
            model.addRow(rowData);
        }
    }
    
    private void doClearTable(){
        while (model.getRowCount()>0){
            model.removeRow(0);
        }   
    }


    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void scrPriceAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_scrPriceAdjustmentValueChanged
       lblPriceInfo.setText(Integer.toString((int) scrPrice.getValue()));
    }//GEN-LAST:event_scrPriceAdjustmentValueChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         model = (DefaultTableModel)tbl.getModel();
        doVivod(tovarOperation.getListOfTovar());
    }//GEN-LAST:event_formWindowOpened

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
  dlgAdd.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddTovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTovarActionPerformed
        dlgAdd.setVisible(false);
        // д.б. код для проверки полей на правильность ввода
        Tovar el;
        if (rdbYesParam.isSelected()) {
            el = new Tovar(cmbName.getSelectedItem().toString(), (int) spnKol.getValue(), scrPrice.getValue());
        } else {
            el = new Tovar();
            el.setName(cmbName.getSelectedItem().toString());
            el.setKol((int) spnKol.getValue());
            el.setPrice(scrPrice.getValue());
        }
        doVivod(tovarOperation.addNewTovar(el));
    }//GEN-LAST:event_btnAddTovarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddTovar;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDecide;
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup btnGrp;
    private javax.swing.JComboBox<String> cmbName;
    private javax.swing.JDialog dlgAdd;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label lbl;
    private javax.swing.JLabel lblKol;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblPriceInfo;
    private javax.swing.JPanel pnlConstruct;
    private javax.swing.JRadioButton rdbNoParam;
    private javax.swing.JRadioButton rdbYesParam;
    private javax.swing.JScrollBar scrPrice;
    private javax.swing.JSpinner spnKol;
    private javax.swing.JToolBar.Separator spr1;
    private javax.swing.JToolBar.Separator spr2;
    private javax.swing.JTable tbl;
    private javax.swing.JToolBar tlBar;
    private java.awt.TextField txtTotalSumma;
    // End of variables declaration//GEN-END:variables

}
