//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://endpoint.service/", ConfigurationName="ServiceReference.ServiceService")]
    public interface ServiceService {
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.service/ServiceService/getAllServiceRequest", ReplyAction="http://endpoint.service/ServiceService/getAllServiceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        client.ServiceReference.getAllServiceResponse getAllService(client.ServiceReference.getAllServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.service/ServiceService/getAllServiceRequest", ReplyAction="http://endpoint.service/ServiceService/getAllServiceResponse")]
        System.Threading.Tasks.Task<client.ServiceReference.getAllServiceResponse> getAllServiceAsync(client.ServiceReference.getAllServiceRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.service/ServiceService/setDelServiceRequest", ReplyAction="http://endpoint.service/ServiceService/setDelServiceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        client.ServiceReference.setDelServiceResponse setDelService(client.ServiceReference.setDelServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.service/ServiceService/setDelServiceRequest", ReplyAction="http://endpoint.service/ServiceService/setDelServiceResponse")]
        System.Threading.Tasks.Task<client.ServiceReference.setDelServiceResponse> setDelServiceAsync(client.ServiceReference.setDelServiceRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.service/ServiceService/setNewServiceRequest", ReplyAction="http://endpoint.service/ServiceService/setNewServiceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        client.ServiceReference.setNewServiceResponse setNewService(client.ServiceReference.setNewServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.service/ServiceService/setNewServiceRequest", ReplyAction="http://endpoint.service/ServiceService/setNewServiceResponse")]
        System.Threading.Tasks.Task<client.ServiceReference.setNewServiceResponse> setNewServiceAsync(client.ServiceReference.setNewServiceRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.service/ServiceService/getSumOfServiceRequest", ReplyAction="http://endpoint.service/ServiceService/getSumOfServiceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        client.ServiceReference.getSumOfServiceResponse getSumOfService(client.ServiceReference.getSumOfServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.service/ServiceService/getSumOfServiceRequest", ReplyAction="http://endpoint.service/ServiceService/getSumOfServiceResponse")]
        System.Threading.Tasks.Task<client.ServiceReference.getSumOfServiceResponse> getSumOfServiceAsync(client.ServiceReference.getSumOfServiceRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://endpoint.service/")]
    public partial class service : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hostelField;
        
        private string masterField;
        
        private string nameField;
        
        private int numberField;
        
        private int priceField;
        
        private string timeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string hostel {
            get {
                return this.hostelField;
            }
            set {
                this.hostelField = value;
                this.RaisePropertyChanged("hostel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string master {
            get {
                return this.masterField;
            }
            set {
                this.masterField = value;
                this.RaisePropertyChanged("master");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllService", WrapperNamespace="http://endpoint.service/", IsWrapped=true)]
    public partial class getAllServiceRequest {
        
        public getAllServiceRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllServiceResponse", WrapperNamespace="http://endpoint.service/", IsWrapped=true)]
    public partial class getAllServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.service/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public client.ServiceReference.service[] @return;
        
        public getAllServiceResponse() {
        }
        
        public getAllServiceResponse(client.ServiceReference.service[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setDelService", WrapperNamespace="http://endpoint.service/", IsWrapped=true)]
    public partial class setDelServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public setDelServiceRequest() {
        }
        
        public setDelServiceRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setDelServiceResponse", WrapperNamespace="http://endpoint.service/", IsWrapped=true)]
    public partial class setDelServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.service/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public client.ServiceReference.service[] @return;
        
        public setDelServiceResponse() {
        }
        
        public setDelServiceResponse(client.ServiceReference.service[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setNewService", WrapperNamespace="http://endpoint.service/", IsWrapped=true)]
    public partial class setNewServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public client.ServiceReference.service arg0;
        
        public setNewServiceRequest() {
        }
        
        public setNewServiceRequest(client.ServiceReference.service arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setNewServiceResponse", WrapperNamespace="http://endpoint.service/", IsWrapped=true)]
    public partial class setNewServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.service/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public client.ServiceReference.service[] @return;
        
        public setNewServiceResponse() {
        }
        
        public setNewServiceResponse(client.ServiceReference.service[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSumOfService", WrapperNamespace="http://endpoint.service/", IsWrapped=true)]
    public partial class getSumOfServiceRequest {
        
        public getSumOfServiceRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSumOfServiceResponse", WrapperNamespace="http://endpoint.service/", IsWrapped=true)]
    public partial class getSumOfServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public getSumOfServiceResponse() {
        }
        
        public getSumOfServiceResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceServiceChannel : client.ServiceReference.ServiceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceServiceClient : System.ServiceModel.ClientBase<client.ServiceReference.ServiceService>, client.ServiceReference.ServiceService {
        
        public ServiceServiceClient() {
        }
        
        public ServiceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client.ServiceReference.getAllServiceResponse client.ServiceReference.ServiceService.getAllService(client.ServiceReference.getAllServiceRequest request) {
            return base.Channel.getAllService(request);
        }
        
        public client.ServiceReference.service[] getAllService() {
            client.ServiceReference.getAllServiceRequest inValue = new client.ServiceReference.getAllServiceRequest();
            client.ServiceReference.getAllServiceResponse retVal = ((client.ServiceReference.ServiceService)(this)).getAllService(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client.ServiceReference.getAllServiceResponse> client.ServiceReference.ServiceService.getAllServiceAsync(client.ServiceReference.getAllServiceRequest request) {
            return base.Channel.getAllServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<client.ServiceReference.getAllServiceResponse> getAllServiceAsync() {
            client.ServiceReference.getAllServiceRequest inValue = new client.ServiceReference.getAllServiceRequest();
            return ((client.ServiceReference.ServiceService)(this)).getAllServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client.ServiceReference.setDelServiceResponse client.ServiceReference.ServiceService.setDelService(client.ServiceReference.setDelServiceRequest request) {
            return base.Channel.setDelService(request);
        }
        
        public client.ServiceReference.service[] setDelService(int arg0) {
            client.ServiceReference.setDelServiceRequest inValue = new client.ServiceReference.setDelServiceRequest();
            inValue.arg0 = arg0;
            client.ServiceReference.setDelServiceResponse retVal = ((client.ServiceReference.ServiceService)(this)).setDelService(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client.ServiceReference.setDelServiceResponse> client.ServiceReference.ServiceService.setDelServiceAsync(client.ServiceReference.setDelServiceRequest request) {
            return base.Channel.setDelServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<client.ServiceReference.setDelServiceResponse> setDelServiceAsync(int arg0) {
            client.ServiceReference.setDelServiceRequest inValue = new client.ServiceReference.setDelServiceRequest();
            inValue.arg0 = arg0;
            return ((client.ServiceReference.ServiceService)(this)).setDelServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client.ServiceReference.setNewServiceResponse client.ServiceReference.ServiceService.setNewService(client.ServiceReference.setNewServiceRequest request) {
            return base.Channel.setNewService(request);
        }
        
        public client.ServiceReference.service[] setNewService(client.ServiceReference.service arg0) {
            client.ServiceReference.setNewServiceRequest inValue = new client.ServiceReference.setNewServiceRequest();
            inValue.arg0 = arg0;
            client.ServiceReference.setNewServiceResponse retVal = ((client.ServiceReference.ServiceService)(this)).setNewService(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client.ServiceReference.setNewServiceResponse> client.ServiceReference.ServiceService.setNewServiceAsync(client.ServiceReference.setNewServiceRequest request) {
            return base.Channel.setNewServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<client.ServiceReference.setNewServiceResponse> setNewServiceAsync(client.ServiceReference.service arg0) {
            client.ServiceReference.setNewServiceRequest inValue = new client.ServiceReference.setNewServiceRequest();
            inValue.arg0 = arg0;
            return ((client.ServiceReference.ServiceService)(this)).setNewServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client.ServiceReference.getSumOfServiceResponse client.ServiceReference.ServiceService.getSumOfService(client.ServiceReference.getSumOfServiceRequest request) {
            return base.Channel.getSumOfService(request);
        }
        
        public int getSumOfService() {
            client.ServiceReference.getSumOfServiceRequest inValue = new client.ServiceReference.getSumOfServiceRequest();
            client.ServiceReference.getSumOfServiceResponse retVal = ((client.ServiceReference.ServiceService)(this)).getSumOfService(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client.ServiceReference.getSumOfServiceResponse> client.ServiceReference.ServiceService.getSumOfServiceAsync(client.ServiceReference.getSumOfServiceRequest request) {
            return base.Channel.getSumOfServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<client.ServiceReference.getSumOfServiceResponse> getSumOfServiceAsync() {
            client.ServiceReference.getSumOfServiceRequest inValue = new client.ServiceReference.getSumOfServiceRequest();
            return ((client.ServiceReference.ServiceService)(this)).getSumOfServiceAsync(inValue);
        }
    }
}
